### ISSUE TITLE
File preambles should follow ELPA conventions

### ISSUE THREAD

**Issue by brdjns-zz** [dlewan/cpio-mode#1]
The file preambles (copyright statements, file description, etc.) should follow the conventions established in other Lisp files in ELPA. I would suggest not including version-control $Id:$ tags as all this information is contained within the repository log anyway.
I can submit a pull request with my changes to that effect if desired.

**Comment by dlewan** [comment]
Files have been updated per ELPA conventions described at http://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/README.
