### ISSUE TITLE
Is cpio-entry-contents-mode missing?

### ISSUE THREAD

**Issue by tarsius** [dlewan/cpio-mode#2]
"cpio-mode.el" requires the feature `cpio-entry-contents-mode`, but I couldn't find anything that provides it.

**Comment by tarsius** [comment]
Friendly ping!

I am asking because I maintain the Emacsmirror and try to make sure that all dependencies of all mirrored packages are satisfied.

**Comment by dlewan** [comment]
The file has been added here and on ELPA.

**Comment by tarsius** [comment]
Thanks!
